// Run: mongosh english_words seed_words.js
// frequency: 1 = most common, higher = less common

db.words.drop();

db.words.insertMany([
  // Top 50 (frequency 1-50)
  { word: "the", transcription: "/ðə/", translation: "определённый артикль", frequency: 1 },
  { word: "be", transcription: "/biː/", translation: "быть, являться", frequency: 2 },
  { word: "to", transcription: "/tuː/", translation: "к, в, до", frequency: 3 },
  { word: "of", transcription: "/ɒv/", translation: "из, от, о", frequency: 4 },
  { word: "and", transcription: "/ænd/", translation: "и, а", frequency: 5 },
  { word: "a", transcription: "/eɪ/", translation: "неопределённый артикль", frequency: 6 },
  { word: "in", transcription: "/ɪn/", translation: "в, внутри", frequency: 7 },
  { word: "that", transcription: "/ðæt/", translation: "тот, что, который", frequency: 8 },
  { word: "have", transcription: "/hæv/", translation: "иметь, обладать", frequency: 9 },
  { word: "I", transcription: "/aɪ/", translation: "я", frequency: 10 },
  { word: "it", transcription: "/ɪt/", translation: "это, он/она/оно", frequency: 11 },
  { word: "for", transcription: "/fɔːr/", translation: "для, за, ради", frequency: 12 },
  { word: "not", transcription: "/nɒt/", translation: "не, нет", frequency: 13 },
  { word: "on", transcription: "/ɒn/", translation: "на, по", frequency: 14 },
  { word: "with", transcription: "/wɪð/", translation: "с, вместе с", frequency: 15 },
  { word: "he", transcription: "/hiː/", translation: "он", frequency: 16 },
  { word: "as", transcription: "/æz/", translation: "как, в качестве", frequency: 17 },
  { word: "you", transcription: "/juː/", translation: "ты, вы", frequency: 18 },
  { word: "do", transcription: "/duː/", translation: "делать, выполнять", frequency: 19 },
  { word: "at", transcription: "/æt/", translation: "в, на, при", frequency: 20 },
  { word: "this", transcription: "/ðɪs/", translation: "этот, эта, это", frequency: 21 },
  { word: "but", transcription: "/bʌt/", translation: "но, однако", frequency: 22 },
  { word: "his", transcription: "/hɪz/", translation: "его", frequency: 23 },
  { word: "by", transcription: "/baɪ/", translation: "у, около, мимо", frequency: 24 },
  { word: "from", transcription: "/frɒm/", translation: "из, от, с", frequency: 25 },
  { word: "they", transcription: "/ðeɪ/", translation: "они", frequency: 26 },
  { word: "we", transcription: "/wiː/", translation: "мы", frequency: 27 },
  { word: "say", transcription: "/seɪ/", translation: "говорить, сказать", frequency: 28 },
  { word: "she", transcription: "/ʃiː/", translation: "она", frequency: 29 },
  { word: "or", transcription: "/ɔːr/", translation: "или", frequency: 30 },
  { word: "an", transcription: "/æn/", translation: "неопределённый артикль", frequency: 31 },
  { word: "will", transcription: "/wɪl/", translation: "буду, будет (будущее)", frequency: 32 },
  { word: "my", transcription: "/maɪ/", translation: "мой, моя, моё", frequency: 33 },
  { word: "one", transcription: "/wʌn/", translation: "один, единый", frequency: 34 },
  { word: "all", transcription: "/ɔːl/", translation: "все, весь, всё", frequency: 35 },
  { word: "would", transcription: "/wʊd/", translation: "бы (условное)", frequency: 36 },
  { word: "there", transcription: "/ðeər/", translation: "там, туда", frequency: 37 },
  { word: "their", transcription: "/ðeər/", translation: "их", frequency: 38 },
  { word: "what", transcription: "/wɒt/", translation: "что, какой", frequency: 39 },
  { word: "so", transcription: "/soʊ/", translation: "так, поэтому", frequency: 40 },
  { word: "up", transcription: "/ʌp/", translation: "вверх, наверх", frequency: 41 },
  { word: "out", transcription: "/aʊt/", translation: "вне, наружу", frequency: 42 },
  { word: "if", transcription: "/ɪf/", translation: "если", frequency: 43 },
  { word: "about", transcription: "/əˈbaʊt/", translation: "о, около, примерно", frequency: 44 },
  { word: "who", transcription: "/huː/", translation: "кто, который", frequency: 45 },
  { word: "get", transcription: "/ɡet/", translation: "получать, доставать", frequency: 46 },
  { word: "which", transcription: "/wɪtʃ/", translation: "который, какой", frequency: 47 },
  { word: "go", transcription: "/ɡoʊ/", translation: "идти, ходить", frequency: 48 },
  { word: "me", transcription: "/miː/", translation: "мне, меня", frequency: 49 },
  { word: "when", transcription: "/wen/", translation: "когда", frequency: 50 },

  // 51-100
  { word: "make", transcription: "/meɪk/", translation: "делать, создавать", frequency: 51 },
  { word: "can", transcription: "/kæn/", translation: "мочь, уметь", frequency: 52 },
  { word: "like", transcription: "/laɪk/", translation: "нравиться, как", frequency: 53 },
  { word: "time", transcription: "/taɪm/", translation: "время", frequency: 54 },
  { word: "no", transcription: "/noʊ/", translation: "нет, никакой", frequency: 55 },
  { word: "just", transcription: "/dʒʌst/", translation: "просто, только что", frequency: 56 },
  { word: "him", transcription: "/hɪm/", translation: "его, ему", frequency: 57 },
  { word: "know", transcription: "/noʊ/", translation: "знать", frequency: 58 },
  { word: "take", transcription: "/teɪk/", translation: "брать, взять", frequency: 59 },
  { word: "people", transcription: "/ˈpiːpl/", translation: "люди, народ", frequency: 60 },
  { word: "into", transcription: "/ˈɪntuː/", translation: "в, внутрь", frequency: 61 },
  { word: "year", transcription: "/jɪər/", translation: "год", frequency: 62 },
  { word: "your", transcription: "/jɔːr/", translation: "твой, ваш", frequency: 63 },
  { word: "good", transcription: "/ɡʊd/", translation: "хороший, добрый", frequency: 64 },
  { word: "some", transcription: "/sʌm/", translation: "некоторый, какой-то", frequency: 65 },
  { word: "could", transcription: "/kʊd/", translation: "мог бы", frequency: 66 },
  { word: "them", transcription: "/ðem/", translation: "их, им", frequency: 67 },
  { word: "see", transcription: "/siː/", translation: "видеть, смотреть", frequency: 68 },
  { word: "other", transcription: "/ˈʌðər/", translation: "другой, иной", frequency: 69 },
  { word: "than", transcription: "/ðæn/", translation: "чем (сравнение)", frequency: 70 },
  { word: "then", transcription: "/ðen/", translation: "тогда, затем", frequency: 71 },
  { word: "now", transcription: "/naʊ/", translation: "сейчас, теперь", frequency: 72 },
  { word: "look", transcription: "/lʊk/", translation: "смотреть, выглядеть", frequency: 73 },
  { word: "only", transcription: "/ˈoʊnli/", translation: "только, единственный", frequency: 74 },
  { word: "come", transcription: "/kʌm/", translation: "приходить, приезжать", frequency: 75 },
  { word: "its", transcription: "/ɪts/", translation: "его, её (притяжат.)", frequency: 76 },
  { word: "over", transcription: "/ˈoʊvər/", translation: "над, через, свыше", frequency: 77 },
  { word: "think", transcription: "/θɪŋk/", translation: "думать, считать", frequency: 78 },
  { word: "also", transcription: "/ˈɔːlsoʊ/", translation: "тоже, также", frequency: 79 },
  { word: "back", transcription: "/bæk/", translation: "назад, спина", frequency: 80 },
  { word: "after", transcription: "/ˈæftər/", translation: "после, за", frequency: 81 },
  { word: "use", transcription: "/juːz/", translation: "использовать", frequency: 82 },
  { word: "two", transcription: "/tuː/", translation: "два", frequency: 83 },
  { word: "how", transcription: "/haʊ/", translation: "как, каким образом", frequency: 84 },
  { word: "our", transcription: "/aʊər/", translation: "наш", frequency: 85 },
  { word: "work", transcription: "/wɜːrk/", translation: "работать, работа", frequency: 86 },
  { word: "first", transcription: "/fɜːrst/", translation: "первый, сначала", frequency: 87 },
  { word: "well", transcription: "/wel/", translation: "хорошо, ну", frequency: 88 },
  { word: "way", transcription: "/weɪ/", translation: "путь, способ", frequency: 89 },
  { word: "even", transcription: "/ˈiːvən/", translation: "даже, ровный", frequency: 90 },
  { word: "new", transcription: "/njuː/", translation: "новый", frequency: 91 },
  { word: "want", transcription: "/wɒnt/", translation: "хотеть, желать", frequency: 92 },
  { word: "because", transcription: "/bɪˈkɒz/", translation: "потому что", frequency: 93 },
  { word: "any", transcription: "/ˈeni/", translation: "любой, какой-нибудь", frequency: 94 },
  { word: "these", transcription: "/ðiːz/", translation: "эти", frequency: 95 },
  { word: "give", transcription: "/ɡɪv/", translation: "давать, дарить", frequency: 96 },
  { word: "day", transcription: "/deɪ/", translation: "день", frequency: 97 },
  { word: "most", transcription: "/moʊst/", translation: "наиболее, большинство", frequency: 98 },
  { word: "us", transcription: "/ʌs/", translation: "нас, нам", frequency: 99 },
  { word: "great", transcription: "/ɡreɪt/", translation: "великий, отличный", frequency: 100 },

  // 101-200
  { word: "find", transcription: "/faɪnd/", translation: "находить, обнаруживать", frequency: 101 },
  { word: "here", transcription: "/hɪər/", translation: "здесь, тут", frequency: 102 },
  { word: "thing", transcription: "/θɪŋ/", translation: "вещь, предмет", frequency: 103 },
  { word: "many", transcription: "/ˈmeni/", translation: "много, многие", frequency: 104 },
  { word: "between", transcription: "/bɪˈtwiːn/", translation: "между", frequency: 105 },
  { word: "keep", transcription: "/kiːp/", translation: "держать, хранить", frequency: 106 },
  { word: "still", transcription: "/stɪl/", translation: "всё ещё, тихий", frequency: 107 },
  { word: "last", transcription: "/læst/", translation: "последний, прошлый", frequency: 108 },
  { word: "long", transcription: "/lɒŋ/", translation: "длинный, долгий", frequency: 109 },
  { word: "tell", transcription: "/tel/", translation: "рассказывать, говорить", frequency: 110 },
  { word: "same", transcription: "/seɪm/", translation: "тот же, одинаковый", frequency: 111 },
  { word: "need", transcription: "/niːd/", translation: "нуждаться, потребность", frequency: 112 },
  { word: "should", transcription: "/ʃʊd/", translation: "следует, должен", frequency: 113 },
  { word: "call", transcription: "/kɔːl/", translation: "звонить, называть", frequency: 114 },
  { word: "world", transcription: "/wɜːrld/", translation: "мир, свет", frequency: 115 },
  { word: "been", transcription: "/biːn/", translation: "был (причастие)", frequency: 116 },
  { word: "may", transcription: "/meɪ/", translation: "может быть, можно", frequency: 117 },
  { word: "much", transcription: "/mʌtʃ/", translation: "много, очень", frequency: 118 },
  { word: "right", transcription: "/raɪt/", translation: "правый, правильный", frequency: 119 },
  { word: "old", transcription: "/oʊld/", translation: "старый", frequency: 120 },
  { word: "too", transcription: "/tuː/", translation: "тоже, слишком", frequency: 121 },
  { word: "does", transcription: "/dʌz/", translation: "делает (3 лицо)", frequency: 122 },
  { word: "own", transcription: "/oʊn/", translation: "собственный, владеть", frequency: 123 },
  { word: "through", transcription: "/θruː/", translation: "через, сквозь", frequency: 124 },
  { word: "show", transcription: "/ʃoʊ/", translation: "показывать, шоу", frequency: 125 },
  { word: "every", transcription: "/ˈevri/", translation: "каждый, всякий", frequency: 126 },
  { word: "hand", transcription: "/hænd/", translation: "рука, кисть", frequency: 127 },
  { word: "high", transcription: "/haɪ/", translation: "высокий", frequency: 128 },
  { word: "again", transcription: "/əˈɡen/", translation: "снова, опять", frequency: 129 },
  { word: "turn", transcription: "/tɜːrn/", translation: "поворачивать, очередь", frequency: 130 },
  { word: "house", transcription: "/haʊs/", translation: "дом", frequency: 131 },
  { word: "before", transcription: "/bɪˈfɔːr/", translation: "до, перед", frequency: 132 },
  { word: "small", transcription: "/smɔːl/", translation: "маленький, малый", frequency: 133 },
  { word: "number", transcription: "/ˈnʌmbər/", translation: "число, номер", frequency: 134 },
  { word: "place", transcription: "/pleɪs/", translation: "место", frequency: 135 },
  { word: "very", transcription: "/ˈveri/", translation: "очень", frequency: 136 },
  { word: "life", transcription: "/laɪf/", translation: "жизнь", frequency: 137 },
  { word: "different", transcription: "/ˈdɪfrənt/", translation: "различный, другой", frequency: 138 },
  { word: "while", transcription: "/waɪl/", translation: "пока, в то время как", frequency: 139 },
  { word: "head", transcription: "/hed/", translation: "голова, глава", frequency: 140 },
  { word: "large", transcription: "/lɑːrdʒ/", translation: "большой, крупный", frequency: 141 },
  { word: "must", transcription: "/mʌst/", translation: "должен, обязан", frequency: 142 },
  { word: "big", transcription: "/bɪɡ/", translation: "большой", frequency: 143 },
  { word: "move", transcription: "/muːv/", translation: "двигать, переезжать", frequency: 144 },
  { word: "might", transcription: "/maɪt/", translation: "мог бы, возможно", frequency: 145 },
  { word: "under", transcription: "/ˈʌndər/", translation: "под, ниже", frequency: 146 },
  { word: "water", transcription: "/ˈwɔːtər/", translation: "вода", frequency: 147 },
  { word: "never", transcription: "/ˈnevər/", translation: "никогда", frequency: 148 },
  { word: "three", transcription: "/θriː/", translation: "три", frequency: 149 },
  { word: "little", transcription: "/ˈlɪtl/", translation: "маленький, немного", frequency: 150 },
  { word: "help", transcription: "/help/", translation: "помогать, помощь", frequency: 151 },
  { word: "put", transcription: "/pʊt/", translation: "класть, ставить", frequency: 152 },
  { word: "start", transcription: "/stɑːrt/", translation: "начинать, старт", frequency: 153 },
  { word: "try", transcription: "/traɪ/", translation: "пытаться, пробовать", frequency: 154 },
  { word: "end", transcription: "/end/", translation: "конец, заканчивать", frequency: 155 },
  { word: "become", transcription: "/bɪˈkʌm/", translation: "становиться", frequency: 156 },
  { word: "begin", transcription: "/bɪˈɡɪn/", translation: "начинать", frequency: 157 },
  { word: "those", transcription: "/ðoʊz/", translation: "те", frequency: 158 },
  { word: "country", transcription: "/ˈkʌntri/", translation: "страна, деревня", frequency: 159 },
  { word: "always", transcription: "/ˈɔːlweɪz/", translation: "всегда", frequency: 160 },
  { word: "name", transcription: "/neɪm/", translation: "имя, название", frequency: 161 },
  { word: "away", transcription: "/əˈweɪ/", translation: "прочь, далеко", frequency: 162 },
  { word: "leave", transcription: "/liːv/", translation: "уходить, оставлять", frequency: 163 },
  { word: "run", transcription: "/rʌn/", translation: "бежать, бегать", frequency: 164 },
  { word: "let", transcription: "/let/", translation: "позволять, пусть", frequency: 165 },
  { word: "part", transcription: "/pɑːrt/", translation: "часть, роль", frequency: 166 },
  { word: "school", transcription: "/skuːl/", translation: "школа", frequency: 167 },
  { word: "point", transcription: "/pɔɪnt/", translation: "точка, суть, указывать", frequency: 168 },
  { word: "read", transcription: "/riːd/", translation: "читать", frequency: 169 },
  { word: "change", transcription: "/tʃeɪndʒ/", translation: "менять, изменение", frequency: 170 },
  { word: "close", transcription: "/kloʊz/", translation: "закрывать, близкий", frequency: 171 },
  { word: "play", transcription: "/pleɪ/", translation: "играть, игра", frequency: 172 },
  { word: "learn", transcription: "/lɜːrn/", translation: "учить, узнавать", frequency: 173 },
  { word: "add", transcription: "/æd/", translation: "добавлять", frequency: 174 },
  { word: "follow", transcription: "/ˈfɒloʊ/", translation: "следовать, следить", frequency: 175 },
  { word: "ask", transcription: "/æsk/", translation: "спрашивать, просить", frequency: 176 },
  { word: "city", transcription: "/ˈsɪti/", translation: "город", frequency: 177 },
  { word: "open", transcription: "/ˈoʊpən/", translation: "открывать, открытый", frequency: 178 },
  { word: "live", transcription: "/lɪv/", translation: "жить", frequency: 179 },
  { word: "seem", transcription: "/siːm/", translation: "казаться", frequency: 180 },
  { word: "side", transcription: "/saɪd/", translation: "сторона, бок", frequency: 181 },
  { word: "set", transcription: "/set/", translation: "устанавливать, набор", frequency: 182 },
  { word: "few", transcription: "/fjuː/", translation: "немногие, мало", frequency: 183 },
  { word: "both", transcription: "/boʊθ/", translation: "оба", frequency: 184 },
  { word: "write", transcription: "/raɪt/", translation: "писать", frequency: 185 },
  { word: "important", transcription: "/ɪmˈpɔːrtənt/", translation: "важный", frequency: 186 },
  { word: "enough", transcription: "/ɪˈnʌf/", translation: "достаточно", frequency: 187 },
  { word: "far", transcription: "/fɑːr/", translation: "далёкий, далеко", frequency: 188 },
  { word: "young", transcription: "/jʌŋ/", translation: "молодой", frequency: 189 },
  { word: "early", transcription: "/ˈɜːrli/", translation: "ранний, рано", frequency: 190 },
  { word: "family", transcription: "/ˈfæməli/", translation: "семья", frequency: 191 },
  { word: "stand", transcription: "/stænd/", translation: "стоять", frequency: 192 },
  { word: "light", transcription: "/laɪt/", translation: "свет, лёгкий", frequency: 193 },
  { word: "later", transcription: "/ˈleɪtər/", translation: "позже, позднее", frequency: 194 },
  { word: "country", transcription: "/ˈkʌntri/", translation: "страна", frequency: 195 },
  { word: "story", transcription: "/ˈstɔːri/", translation: "история, рассказ", frequency: 196 },
  { word: "fact", transcription: "/fækt/", translation: "факт", frequency: 197 },
  { word: "money", transcription: "/ˈmʌni/", translation: "деньги", frequency: 198 },
  { word: "problem", transcription: "/ˈprɒbləm/", translation: "проблема", frequency: 199 },
  { word: "idea", transcription: "/aɪˈdɪə/", translation: "идея, мысль", frequency: 200 },

  // 201-350 — more useful vocabulary
  { word: "believe", transcription: "/bɪˈliːv/", translation: "верить, полагать", frequency: 201 },
  { word: "power", transcription: "/ˈpaʊər/", translation: "сила, власть", frequency: 202 },
  { word: "watch", transcription: "/wɒtʃ/", translation: "смотреть, часы", frequency: 203 },
  { word: "remember", transcription: "/rɪˈmembər/", translation: "помнить, вспоминать", frequency: 204 },
  { word: "often", transcription: "/ˈɒfən/", translation: "часто", frequency: 205 },
  { word: "stop", transcription: "/stɒp/", translation: "останавливать", frequency: 206 },
  { word: "talk", transcription: "/tɔːk/", translation: "разговаривать, беседа", frequency: 207 },
  { word: "experience", transcription: "/ɪkˈspɪəriəns/", translation: "опыт, переживание", frequency: 208 },
  { word: "body", transcription: "/ˈbɒdi/", translation: "тело", frequency: 209 },
  { word: "question", transcription: "/ˈkwestʃən/", translation: "вопрос", frequency: 210 },
  { word: "morning", transcription: "/ˈmɔːrnɪŋ/", translation: "утро", frequency: 211 },
  { word: "reach", transcription: "/riːtʃ/", translation: "достигать, добираться", frequency: 212 },
  { word: "stay", transcription: "/steɪ/", translation: "оставаться", frequency: 213 },
  { word: "understand", transcription: "/ˌʌndərˈstænd/", translation: "понимать", frequency: 214 },
  { word: "door", transcription: "/dɔːr/", translation: "дверь", frequency: 215 },
  { word: "bring", transcription: "/brɪŋ/", translation: "приносить", frequency: 216 },
  { word: "happen", transcription: "/ˈhæpən/", translation: "случаться, происходить", frequency: 217 },
  { word: "hold", transcription: "/hoʊld/", translation: "держать, удерживать", frequency: 218 },
  { word: "speak", transcription: "/spiːk/", translation: "говорить, разговаривать", frequency: 219 },
  { word: "real", transcription: "/rɪəl/", translation: "настоящий, реальный", frequency: 220 },
  { word: "mean", transcription: "/miːn/", translation: "означать, иметь в виду", frequency: 221 },
  { word: "grow", transcription: "/ɡroʊ/", translation: "расти, выращивать", frequency: 222 },
  { word: "build", transcription: "/bɪld/", translation: "строить, создавать", frequency: 223 },
  { word: "earth", transcription: "/ɜːrθ/", translation: "земля, планета", frequency: 224 },
  { word: "possible", transcription: "/ˈpɒsəbl/", translation: "возможный", frequency: 225 },
  { word: "answer", transcription: "/ˈænsər/", translation: "ответ, отвечать", frequency: 226 },
  { word: "receive", transcription: "/rɪˈsiːv/", translation: "получать, принимать", frequency: 227 },
  { word: "study", transcription: "/ˈstʌdi/", translation: "изучать, учёба", frequency: 228 },
  { word: "develop", transcription: "/dɪˈveləp/", translation: "развивать, разрабатывать", frequency: 229 },
  { word: "human", transcription: "/ˈhjuːmən/", translation: "человеческий, человек", frequency: 230 },
  { word: "food", transcription: "/fuːd/", translation: "еда, пища", frequency: 231 },
  { word: "spend", transcription: "/spend/", translation: "тратить, проводить", frequency: 232 },
  { word: "language", transcription: "/ˈlæŋɡwɪdʒ/", translation: "язык (речь)", frequency: 233 },
  { word: "mother", transcription: "/ˈmʌðər/", translation: "мать", frequency: 234 },
  { word: "father", transcription: "/ˈfɑːðər/", translation: "отец", frequency: 235 },
  { word: "friend", transcription: "/frend/", translation: "друг", frequency: 236 },
  { word: "woman", transcription: "/ˈwʊmən/", translation: "женщина", frequency: 237 },
  { word: "child", transcription: "/tʃaɪld/", translation: "ребёнок", frequency: 238 },
  { word: "table", transcription: "/ˈteɪbl/", translation: "стол, таблица", frequency: 239 },
  { word: "walk", transcription: "/wɔːk/", translation: "ходить, гулять", frequency: 240 },
  { word: "white", transcription: "/waɪt/", translation: "белый", frequency: 241 },
  { word: "black", transcription: "/blæk/", translation: "чёрный", frequency: 242 },
  { word: "strong", transcription: "/strɒŋ/", translation: "сильный, крепкий", frequency: 243 },
  { word: "true", transcription: "/truː/", translation: "правдивый, верный", frequency: 244 },
  { word: "sure", transcription: "/ʃʊər/", translation: "уверенный, конечно", frequency: 245 },
  { word: "clear", transcription: "/klɪər/", translation: "ясный, чистый", frequency: 246 },
  { word: "happy", transcription: "/ˈhæpi/", translation: "счастливый", frequency: 247 },
  { word: "beautiful", transcription: "/ˈbjuːtɪfl/", translation: "красивый", frequency: 248 },
  { word: "simple", transcription: "/ˈsɪmpl/", translation: "простой", frequency: 249 },
  { word: "free", transcription: "/friː/", translation: "свободный, бесплатный", frequency: 250 },
  { word: "hard", transcription: "/hɑːrd/", translation: "трудный, твёрдый", frequency: 251 },
  { word: "behind", transcription: "/bɪˈhaɪnd/", translation: "позади, за", frequency: 252 },
  { word: "listen", transcription: "/ˈlɪsn/", translation: "слушать", frequency: 253 },
  { word: "create", transcription: "/kriˈeɪt/", translation: "создавать, творить", frequency: 254 },
  { word: "decide", transcription: "/dɪˈsaɪd/", translation: "решать", frequency: 255 },
  { word: "explain", transcription: "/ɪkˈspleɪn/", translation: "объяснять", frequency: 256 },
  { word: "wonder", transcription: "/ˈwʌndər/", translation: "удивляться, чудо", frequency: 257 },
  { word: "consider", transcription: "/kənˈsɪdər/", translation: "рассматривать, считать", frequency: 258 },
  { word: "suggest", transcription: "/səˈdʒest/", translation: "предлагать", frequency: 259 },
  { word: "continue", transcription: "/kənˈtɪnjuː/", translation: "продолжать", frequency: 260 },
  { word: "expect", transcription: "/ɪkˈspekt/", translation: "ожидать", frequency: 261 },
  { word: "produce", transcription: "/prəˈdjuːs/", translation: "производить", frequency: 262 },
  { word: "provide", transcription: "/prəˈvaɪd/", translation: "предоставлять", frequency: 263 },
  { word: "include", transcription: "/ɪnˈkluːd/", translation: "включать, содержать", frequency: 264 },
  { word: "require", transcription: "/rɪˈkwaɪər/", translation: "требовать", frequency: 265 },
  { word: "agree", transcription: "/əˈɡriː/", translation: "соглашаться", frequency: 266 },
  { word: "offer", transcription: "/ˈɒfər/", translation: "предлагать, предложение", frequency: 267 },
  { word: "prepare", transcription: "/prɪˈpeər/", translation: "готовить, подготавливать", frequency: 268 },
  { word: "suppose", transcription: "/səˈpoʊz/", translation: "предполагать, полагать", frequency: 269 },
  { word: "enjoy", transcription: "/ɪnˈdʒɔɪ/", translation: "наслаждаться", frequency: 270 },
  { word: "imagine", transcription: "/ɪˈmædʒɪn/", translation: "воображать, представлять", frequency: 271 },
  { word: "accept", transcription: "/əkˈsept/", translation: "принимать, соглашаться", frequency: 272 },
  { word: "allow", transcription: "/əˈlaʊ/", translation: "позволять, разрешать", frequency: 273 },
  { word: "compare", transcription: "/kəmˈpeər/", translation: "сравнивать", frequency: 274 },
  { word: "contain", transcription: "/kənˈteɪn/", translation: "содержать, вмещать", frequency: 275 },
  { word: "choose", transcription: "/tʃuːz/", translation: "выбирать", frequency: 276 },
  { word: "surprise", transcription: "/sərˈpraɪz/", translation: "удивлять, сюрприз", frequency: 277 },
  { word: "protect", transcription: "/prəˈtekt/", translation: "защищать", frequency: 278 },
  { word: "improve", transcription: "/ɪmˈpruːv/", translation: "улучшать", frequency: 279 },
  { word: "destroy", transcription: "/dɪˈstrɔɪ/", translation: "разрушать, уничтожать", frequency: 280 },
  { word: "describe", transcription: "/dɪˈskraɪb/", translation: "описывать", frequency: 281 },
  { word: "discover", transcription: "/dɪˈskʌvər/", translation: "обнаруживать, открывать", frequency: 282 },
  { word: "involve", transcription: "/ɪnˈvɒlv/", translation: "вовлекать, включать", frequency: 283 },
  { word: "result", transcription: "/rɪˈzʌlt/", translation: "результат", frequency: 284 },
  { word: "appear", transcription: "/əˈpɪər/", translation: "появляться, казаться", frequency: 285 },
  { word: "achieve", transcription: "/əˈtʃiːv/", translation: "достигать, добиваться", frequency: 286 },
  { word: "knowledge", transcription: "/ˈnɒlɪdʒ/", translation: "знание", frequency: 287 },
  { word: "situation", transcription: "/ˌsɪtʃuˈeɪʃən/", translation: "ситуация, положение", frequency: 288 },
  { word: "society", transcription: "/səˈsaɪəti/", translation: "общество", frequency: 289 },
  { word: "perhaps", transcription: "/pərˈhæps/", translation: "возможно, может быть", frequency: 290 },
  { word: "position", transcription: "/pəˈzɪʃən/", translation: "положение, позиция", frequency: 291 },
  { word: "history", transcription: "/ˈhɪstəri/", translation: "история", frequency: 292 },
  { word: "attention", transcription: "/əˈtenʃən/", translation: "внимание", frequency: 293 },
  { word: "common", transcription: "/ˈkɒmən/", translation: "общий, обычный", frequency: 294 },
  { word: "various", transcription: "/ˈveəriəs/", translation: "различный, разнообразный", frequency: 295 },
  { word: "natural", transcription: "/ˈnætʃərəl/", translation: "природный, естественный", frequency: 296 },
  { word: "international", transcription: "/ˌɪntərˈnæʃənəl/", translation: "международный", frequency: 297 },
  { word: "political", transcription: "/pəˈlɪtɪkəl/", translation: "политический", frequency: 298 },
  { word: "economic", transcription: "/ˌiːkəˈnɒmɪk/", translation: "экономический", frequency: 299 },
  { word: "social", transcription: "/ˈsoʊʃəl/", translation: "социальный, общественный", frequency: 300 },
  { word: "special", transcription: "/ˈspeʃəl/", translation: "особый, специальный", frequency: 301 },
  { word: "possible", transcription: "/ˈpɒsəbl/", translation: "возможный", frequency: 302 },
  { word: "available", transcription: "/əˈveɪləbl/", translation: "доступный, имеющийся", frequency: 303 },
  { word: "necessary", transcription: "/ˈnesəsəri/", translation: "необходимый", frequency: 304 },
  { word: "difficult", transcription: "/ˈdɪfɪkəlt/", translation: "трудный, сложный", frequency: 305 },
  { word: "significant", transcription: "/sɪɡˈnɪfɪkənt/", translation: "значительный, важный", frequency: 306 },
  { word: "similar", transcription: "/ˈsɪmɪlər/", translation: "похожий, подобный", frequency: 307 },
  { word: "popular", transcription: "/ˈpɒpjʊlər/", translation: "популярный, народный", frequency: 308 },
  { word: "traditional", transcription: "/trəˈdɪʃənəl/", translation: "традиционный", frequency: 309 },
  { word: "environment", transcription: "/ɪnˈvaɪrənmənt/", translation: "окружающая среда", frequency: 310 },
  { word: "technology", transcription: "/tekˈnɒlədʒi/", translation: "технология", frequency: 311 },
  { word: "education", transcription: "/ˌedjʊˈkeɪʃən/", translation: "образование", frequency: 312 },
  { word: "community", transcription: "/kəˈmjuːnəti/", translation: "сообщество", frequency: 313 },
  { word: "relationship", transcription: "/rɪˈleɪʃənʃɪp/", translation: "отношения, связь", frequency: 314 },
  { word: "opportunity", transcription: "/ˌɒpərˈtjuːnəti/", translation: "возможность, шанс", frequency: 315 },
  { word: "responsibility", transcription: "/rɪˌspɒnsəˈbɪləti/", translation: "ответственность", frequency: 316 },
  { word: "information", transcription: "/ˌɪnfərˈmeɪʃən/", translation: "информация", frequency: 317 },
  { word: "government", transcription: "/ˈɡʌvərnmənt/", translation: "правительство", frequency: 318 },
  { word: "development", transcription: "/dɪˈveləpmənt/", translation: "развитие", frequency: 319 },
  { word: "management", transcription: "/ˈmænɪdʒmənt/", translation: "управление, менеджмент", frequency: 320 },
  { word: "difference", transcription: "/ˈdɪfrəns/", translation: "разница, отличие", frequency: 321 },
  { word: "performance", transcription: "/pərˈfɔːrməns/", translation: "выступление, производительность", frequency: 322 },
  { word: "conversation", transcription: "/ˌkɒnvərˈseɪʃən/", translation: "разговор, беседа", frequency: 323 },
  { word: "temperature", transcription: "/ˈtemprətʃər/", translation: "температура", frequency: 324 },
  { word: "comfortable", transcription: "/ˈkʌmftəbl/", translation: "удобный, комфортный", frequency: 325 },
  { word: "dangerous", transcription: "/ˈdeɪndʒərəs/", translation: "опасный", frequency: 326 },
  { word: "independent", transcription: "/ˌɪndɪˈpendənt/", translation: "независимый", frequency: 327 },
  { word: "unfortunately", transcription: "/ʌnˈfɔːrtʃənətli/", translation: "к сожалению", frequency: 328 },
  { word: "immediately", transcription: "/ɪˈmiːdiətli/", translation: "немедленно, сразу", frequency: 329 },
  { word: "especially", transcription: "/ɪˈspeʃəli/", translation: "особенно", frequency: 330 },
  { word: "absolutely", transcription: "/ˈæbsəluːtli/", translation: "абсолютно, совершенно", frequency: 331 },
  { word: "actually", transcription: "/ˈæktʃuəli/", translation: "на самом деле, фактически", frequency: 332 },
  { word: "certainly", transcription: "/ˈsɜːrtnli/", translation: "конечно, безусловно", frequency: 333 },
  { word: "obviously", transcription: "/ˈɒbviəsli/", translation: "очевидно", frequency: 334 },
  { word: "probably", transcription: "/ˈprɒbəbli/", translation: "вероятно, наверное", frequency: 335 },
  { word: "generally", transcription: "/ˈdʒenərəli/", translation: "обычно, в целом", frequency: 336 },
  { word: "recently", transcription: "/ˈriːsntli/", translation: "недавно", frequency: 337 },
  { word: "suddenly", transcription: "/ˈsʌdənli/", translation: "вдруг, внезапно", frequency: 338 },
  { word: "completely", transcription: "/kəmˈpliːtli/", translation: "полностью, совершенно", frequency: 339 },
  { word: "eventually", transcription: "/ɪˈventʃuəli/", translation: "в конце концов", frequency: 340 },
  { word: "apparently", transcription: "/əˈpærəntli/", translation: "по-видимому, очевидно", frequency: 341 },
  { word: "approximately", transcription: "/əˈprɒksɪmətli/", translation: "приблизительно", frequency: 342 },
  { word: "meanwhile", transcription: "/ˈmiːnwaɪl/", translation: "тем временем", frequency: 343 },
  { word: "therefore", transcription: "/ˈðeərfɔːr/", translation: "поэтому, следовательно", frequency: 344 },
  { word: "although", transcription: "/ɔːlˈðoʊ/", translation: "хотя, несмотря на", frequency: 345 },
  { word: "however", transcription: "/haʊˈevər/", translation: "однако, тем не менее", frequency: 346 },
  { word: "whether", transcription: "/ˈweðər/", translation: "ли, будь то", frequency: 347 },
  { word: "neither", transcription: "/ˈniːðər/", translation: "ни тот ни другой", frequency: 348 },
  { word: "nevertheless", transcription: "/ˌnevərðəˈles/", translation: "тем не менее, всё же", frequency: 349 },
  { word: "extraordinary", transcription: "/ɪkˈstrɔːrdəneri/", translation: "необычайный, выдающийся", frequency: 350 },
]);

db.words.createIndex({ frequency: 1 });

print("Inserted " + db.words.countDocuments() + " words");
