// Run: mongosh english_words seed_words.js
// frequency: 1 = most common, higher = less common
// example: short usage sentence shown on the card (optional per word)

db.words.drop();

db.words.insertMany([
  // Top 50 (frequency 1-50)
  { word: "the", transcription: "/ðə/", translation: "определённый артикль", frequency: 1, example: "The dog is in the garden." },
  { word: "be", transcription: "/biː/", translation: "быть, являться", frequency: 2, example: "I want to be a doctor." },
  { word: "to", transcription: "/tuː/", translation: "к, в, до", frequency: 3, example: "We are going to the park." },
  { word: "of", transcription: "/ɒv/", translation: "из, от, о", frequency: 4, example: "This is a cup of tea." },
  { word: "and", transcription: "/ænd/", translation: "и, а", frequency: 5, example: "I like tea and coffee." },
  { word: "a", transcription: "/eɪ/", translation: "неопределённый артикль", frequency: 6, example: "She has a new car." },
  { word: "in", transcription: "/ɪn/", translation: "в, внутри", frequency: 7, example: "The keys are in my bag." },
  { word: "that", transcription: "/ðæt/", translation: "тот, что, который", frequency: 8, example: "That book is very good." },
  { word: "have", transcription: "/hæv/", translation: "иметь, обладать", frequency: 9, example: "I have two brothers." },
  { word: "I", transcription: "/aɪ/", translation: "я", frequency: 10, example: "I live in a small town." },
  { word: "it", transcription: "/ɪt/", translation: "это, он/она/оно", frequency: 11, example: "It is raining today." },
  { word: "for", transcription: "/fɔːr/", translation: "для, за, ради", frequency: 12, example: "This gift is for you." },
  { word: "not", transcription: "/nɒt/", translation: "не, нет", frequency: 13, example: "She is not at home." },
  { word: "on", transcription: "/ɒn/", translation: "на, по", frequency: 14, example: "The book is on the table." },
  { word: "with", transcription: "/wɪð/", translation: "с, вместе с", frequency: 15, example: "I went there with my friend." },
  { word: "he", transcription: "/hiː/", translation: "он", frequency: 16, example: "He works in a bank." },
  { word: "as", transcription: "/æz/", translation: "как, в качестве", frequency: 17, example: "She works as a teacher." },
  { word: "you", transcription: "/juː/", translation: "ты, вы", frequency: 18, example: "Can you help me, please?" },
  { word: "do", transcription: "/duː/", translation: "делать, выполнять", frequency: 19, example: "What do you do here?" },
  { word: "at", transcription: "/æt/", translation: "в, на, при", frequency: 20, example: "We meet at the station." },
  { word: "this", transcription: "/ðɪs/", translation: "этот, эта, это", frequency: 21, example: "This is my new phone." },
  { word: "but", transcription: "/bʌt/", translation: "но, однако", frequency: 22, example: "I am tired, but happy." },
  { word: "his", transcription: "/hɪz/", translation: "его", frequency: 23, example: "His name is Tom." },
  { word: "by", transcription: "/baɪ/", translation: "у, около, мимо", frequency: 24, example: "She sat by the window." },
  { word: "from", transcription: "/frɒm/", translation: "из, от, с", frequency: 25, example: "I am from Russia." },
  { word: "they", transcription: "/ðeɪ/", translation: "они", frequency: 26, example: "They live next door." },
  { word: "we", transcription: "/wiː/", translation: "мы", frequency: 27, example: "We are good friends." },
  { word: "say", transcription: "/seɪ/", translation: "говорить, сказать", frequency: 28, example: "Please say it again." },
  { word: "she", transcription: "/ʃiː/", translation: "она", frequency: 29, example: "She likes to read books." },
  { word: "or", transcription: "/ɔːr/", translation: "или", frequency: 30, example: "Tea or coffee?" },
  { word: "an", transcription: "/æn/", translation: "неопределённый артикль", frequency: 31, example: "I ate an apple." },
  { word: "will", transcription: "/wɪl/", translation: "буду, будет (будущее)", frequency: 32, example: "I will call you tomorrow." },
  { word: "my", transcription: "/maɪ/", translation: "мой, моя, моё", frequency: 33, example: "This is my house." },
  { word: "one", transcription: "/wʌn/", translation: "один, единый", frequency: 34, example: "I have only one sister." },
  { word: "all", transcription: "/ɔːl/", translation: "все, весь, всё", frequency: 35, example: "All the children are here." },
  { word: "would", transcription: "/wʊd/", translation: "бы (условное)", frequency: 36, example: "I would like some water." },
  { word: "there", transcription: "/ðeər/", translation: "там, туда", frequency: 37, example: "Your bag is over there." },
  { word: "their", transcription: "/ðeər/", translation: "их", frequency: 38, example: "Their house is big." },
  { word: "what", transcription: "/wɒt/", translation: "что, какой", frequency: 39, example: "What is your name?" },
  { word: "so", transcription: "/soʊ/", translation: "так, поэтому", frequency: 40, example: "I was so tired." },
  { word: "up", transcription: "/ʌp/", translation: "вверх, наверх", frequency: 41, example: "Please stand up." },
  { word: "out", transcription: "/aʊt/", translation: "вне, наружу", frequency: 42, example: "Let's go out tonight." },
  { word: "if", transcription: "/ɪf/", translation: "если", frequency: 43, example: "Call me if you need help." },
  { word: "about", transcription: "/əˈbaʊt/", translation: "о, около, примерно", frequency: 44, example: "We talked about the film." },
  { word: "who", transcription: "/huː/", translation: "кто, который", frequency: 45, example: "Who is that man?" },
  { word: "get", transcription: "/ɡet/", translation: "получать, доставать", frequency: 46, example: "I need to get some milk." },
  { word: "which", transcription: "/wɪtʃ/", translation: "который, какой", frequency: 47, example: "Which book do you want?" },
  { word: "go", transcription: "/ɡoʊ/", translation: "идти, ходить", frequency: 48, example: "Let's go to the beach." },
  { word: "me", transcription: "/miː/", translation: "мне, меня", frequency: 49, example: "Please give it to me." },
  { word: "when", transcription: "/wen/", translation: "когда", frequency: 50, example: "Call me when you arrive." },
  // 51-100
  { word: "make", transcription: "/meɪk/", translation: "делать, создавать", frequency: 51, example: "Let's make a cake today." },
  { word: "can", transcription: "/kæn/", translation: "мочь, уметь", frequency: 52, example: "I can swim very well." },
  { word: "like", transcription: "/laɪk/", translation: "нравиться, как", frequency: 53, example: "I like coffee in the morning." },
  { word: "time", transcription: "/taɪm/", translation: "время", frequency: 54, example: "What time is it now?" },
  { word: "no", transcription: "/noʊ/", translation: "нет, никакой", frequency: 55, example: "There is no milk left." },
  { word: "just", transcription: "/dʒʌst/", translation: "просто, только что", frequency: 56, example: "I just woke up." },
  { word: "him", transcription: "/hɪm/", translation: "его, ему", frequency: 57, example: "Please give the book to him." },
  { word: "know", transcription: "/noʊ/", translation: "знать", frequency: 58, example: "I know the answer." },
  { word: "take", transcription: "/teɪk/", translation: "брать, взять", frequency: 59, example: "Take your jacket with you." },
  { word: "people", transcription: "/ˈpiːpl/", translation: "люди, народ", frequency: 60, example: "Many people like music." },
  { word: "into", transcription: "/ˈɪntuː/", translation: "в, внутрь", frequency: 61, example: "She walked into the room." },
  { word: "year", transcription: "/jɪər/", translation: "год", frequency: 62, example: "We meet once a year." },
  { word: "your", transcription: "/jɔːr/", translation: "твой, ваш", frequency: 63, example: "Where is your bag?" },
  { word: "good", transcription: "/ɡʊd/", translation: "хороший, добрый", frequency: 64, example: "This is a good book." },
  { word: "some", transcription: "/sʌm/", translation: "некоторый, какой-то", frequency: 65, example: "I need some water." },
  { word: "could", transcription: "/kʊd/", translation: "мог бы", frequency: 66, example: "Could you help me, please?" },
  { word: "them", transcription: "/ðem/", translation: "их, им", frequency: 67, example: "I gave them my keys." },
  { word: "see", transcription: "/siː/", translation: "видеть, смотреть", frequency: 68, example: "I can see the moon." },
  { word: "other", transcription: "/ˈʌðər/", translation: "другой, иной", frequency: 69, example: "Try the other door." },
  { word: "than", transcription: "/ðæn/", translation: "чем (сравнение)", frequency: 70, example: "She is taller than me." },
  { word: "then", transcription: "/ðen/", translation: "тогда, затем", frequency: 71, example: "We ate, then we left." },
  { word: "now", transcription: "/naʊ/", translation: "сейчас, теперь", frequency: 72, example: "I am busy right now." },
  { word: "look", transcription: "/lʊk/", translation: "смотреть, выглядеть", frequency: 73, example: "Look at this photo." },
  { word: "only", transcription: "/ˈoʊnli/", translation: "только, единственный", frequency: 74, example: "I have only one pen." },
  { word: "come", transcription: "/kʌm/", translation: "приходить, приезжать", frequency: 75, example: "Please come to my house." },
  { word: "its", transcription: "/ɪts/", translation: "его, её (притяжат.)", frequency: 76, example: "The dog wags its tail." },
  { word: "over", transcription: "/ˈoʊvər/", translation: "над, через, свыше", frequency: 77, example: "The bridge goes over the river." },
  { word: "think", transcription: "/θɪŋk/", translation: "думать, считать", frequency: 78, example: "I think you are right." },
  { word: "also", transcription: "/ˈɔːlsoʊ/", translation: "тоже, также", frequency: 79, example: "I also want some tea." },
  { word: "back", transcription: "/bæk/", translation: "назад, спина", frequency: 80, example: "He is coming back soon." },
  { word: "after", transcription: "/ˈæftər/", translation: "после, за", frequency: 81, example: "We rest after lunch." },
  { word: "use", transcription: "/juːz/", translation: "использовать", frequency: 82, example: "I use a pen to write." },
  { word: "two", transcription: "/tuː/", translation: "два", frequency: 83, example: "I have two brothers." },
  { word: "how", transcription: "/haʊ/", translation: "как, каким образом", frequency: 84, example: "How are you today?" },
  { word: "our", transcription: "/aʊər/", translation: "наш", frequency: 85, example: "This is our new car." },
  { word: "work", transcription: "/wɜːrk/", translation: "работать, работа", frequency: 86, example: "I work in an office." },
  { word: "first", transcription: "/fɜːrst/", translation: "первый, сначала", frequency: 87, example: "This is my first day." },
  { word: "well", transcription: "/wel/", translation: "хорошо, ну", frequency: 88, example: "She sings very well." },
  { word: "way", transcription: "/weɪ/", translation: "путь, способ", frequency: 89, example: "This is the right way." },
  { word: "even", transcription: "/ˈiːvən/", translation: "даже, ровный", frequency: 90, example: "He works even on Sundays." },
  { word: "new", transcription: "/njuː/", translation: "новый", frequency: 91, example: "I bought a new phone." },
  { word: "want", transcription: "/wɒnt/", translation: "хотеть, желать", frequency: 92, example: "I want some ice cream." },
  { word: "because", transcription: "/bɪˈkɒz/", translation: "потому что", frequency: 93, example: "I stayed home because it rained." },
  { word: "any", transcription: "/ˈeni/", translation: "любой, какой-нибудь", frequency: 94, example: "Do you have any questions?" },
  { word: "these", transcription: "/ðiːz/", translation: "эти", frequency: 95, example: "These shoes are too small." },
  { word: "give", transcription: "/ɡɪv/", translation: "давать, дарить", frequency: 96, example: "Give me your hand." },
  { word: "day", transcription: "/deɪ/", translation: "день", frequency: 97, example: "It is a sunny day." },
  { word: "most", transcription: "/moʊst/", translation: "наиболее, большинство", frequency: 98, example: "Most kids like candy." },
  { word: "us", transcription: "/ʌs/", translation: "нас, нам", frequency: 99, example: "Come with us to the park." },
  { word: "great", transcription: "/ɡreɪt/", translation: "великий, отличный", frequency: 100, example: "We had a great time." },
  // 101-200
  { word: "find", transcription: "/faɪnd/", translation: "находить, обнаруживать", frequency: 101, example: "I can't find my keys." },
  { word: "here", transcription: "/hɪər/", translation: "здесь, тут", frequency: 102, example: "Please sit here." },
  { word: "thing", transcription: "/θɪŋ/", translation: "вещь, предмет", frequency: 103, example: "What is that thing?" },
  { word: "many", transcription: "/ˈmeni/", translation: "много, многие", frequency: 104, example: "She has many friends." },
  { word: "between", transcription: "/bɪˈtwiːn/", translation: "между", frequency: 105, example: "Sit between us." },
  { word: "keep", transcription: "/kiːp/", translation: "держать, хранить", frequency: 106, example: "Please keep the door open." },
  { word: "still", transcription: "/stɪl/", translation: "всё ещё, тихий", frequency: 107, example: "He is still asleep." },
  { word: "last", transcription: "/læst/", translation: "последний, прошлый", frequency: 108, example: "I saw her last week." },
  { word: "long", transcription: "/lɒŋ/", translation: "длинный, долгий", frequency: 109, example: "It was a long day." },
  { word: "tell", transcription: "/tel/", translation: "рассказывать, говорить", frequency: 110, example: "Tell me the truth." },
  { word: "same", transcription: "/seɪm/", translation: "тот же, одинаковый", frequency: 111, example: "We like the same food." },
  { word: "need", transcription: "/niːd/", translation: "нуждаться, потребность", frequency: 112, example: "I need some water." },
  { word: "should", transcription: "/ʃʊd/", translation: "следует, должен", frequency: 113, example: "You should eat now." },
  { word: "call", transcription: "/kɔːl/", translation: "звонить, называть", frequency: 114, example: "I will call you later." },
  { word: "world", transcription: "/wɜːrld/", translation: "мир, свет", frequency: 115, example: "She wants to see the world." },
  { word: "been", transcription: "/biːn/", translation: "был (причастие)", frequency: 116, example: "I have been here before." },
  { word: "may", transcription: "/meɪ/", translation: "может быть, можно", frequency: 117, example: "It may rain today." },
  { word: "much", transcription: "/mʌtʃ/", translation: "много, очень", frequency: 118, example: "I love you so much." },
  { word: "right", transcription: "/raɪt/", translation: "правый, правильный", frequency: 119, example: "Turn right at the corner." },
  { word: "old", transcription: "/oʊld/", translation: "старый", frequency: 120, example: "My car is very old." },
  { word: "too", transcription: "/tuː/", translation: "тоже, слишком", frequency: 121, example: "It is too hot today." },
  { word: "does", transcription: "/dʌz/", translation: "делает (3 лицо)", frequency: 122, example: "Does she speak English?" },
  { word: "own", transcription: "/oʊn/", translation: "собственный, владеть", frequency: 123, example: "I have my own room." },
  { word: "through", transcription: "/θruː/", translation: "через, сквозь", frequency: 124, example: "We walked through the park." },
  { word: "show", transcription: "/ʃoʊ/", translation: "показывать, шоу", frequency: 125, example: "Show me your new phone." },
  { word: "every", transcription: "/ˈevri/", translation: "каждый, всякий", frequency: 126, example: "I run every morning." },
  { word: "hand", transcription: "/hænd/", translation: "рука, кисть", frequency: 127, example: "Raise your hand to ask." },
  { word: "high", transcription: "/haɪ/", translation: "высокий", frequency: 128, example: "The wall is very high." },
  { word: "again", transcription: "/əˈɡen/", translation: "снова, опять", frequency: 129, example: "Please say that again." },
  { word: "turn", transcription: "/tɜːrn/", translation: "поворачивать, очередь", frequency: 130, example: "It is your turn now." },
  { word: "house", transcription: "/haʊs/", translation: "дом", frequency: 131, example: "They live in a big house." },
  { word: "before", transcription: "/bɪˈfɔːr/", translation: "до, перед", frequency: 132, example: "Call me before lunch." },
  { word: "small", transcription: "/smɔːl/", translation: "маленький, малый", frequency: 133, example: "This is a small box." },
  { word: "number", transcription: "/ˈnʌmbər/", translation: "число, номер", frequency: 134, example: "What is your phone number?" },
  { word: "place", transcription: "/pleɪs/", translation: "место", frequency: 135, example: "This is a quiet place." },
  { word: "very", transcription: "/ˈveri/", translation: "очень", frequency: 136, example: "She is very kind." },
  { word: "life", transcription: "/laɪf/", translation: "жизнь", frequency: 137, example: "He has a happy life." },
  { word: "different", transcription: "/ˈdɪfrənt/", translation: "различный, другой", frequency: 138, example: "We have different ideas." },
  { word: "while", transcription: "/waɪl/", translation: "пока, в то время как", frequency: 139, example: "Wait here for a while." },
  { word: "head", transcription: "/hed/", translation: "голова, глава", frequency: 140, example: "My head hurts a little." },
  { word: "large", transcription: "/lɑːrdʒ/", translation: "большой, крупный", frequency: 141, example: "They have a large garden." },
  { word: "must", transcription: "/mʌst/", translation: "должен, обязан", frequency: 142, example: "You must wear a coat." },
  { word: "big", transcription: "/bɪɡ/", translation: "большой", frequency: 143, example: "That is a big dog." },
  { word: "move", transcription: "/muːv/", translation: "двигать, переезжать", frequency: 144, example: "We will move next month." },
  { word: "might", transcription: "/maɪt/", translation: "мог бы, возможно", frequency: 145, example: "She might come later." },
  { word: "under", transcription: "/ˈʌndər/", translation: "под, ниже", frequency: 146, example: "The cat is under the table." },
  { word: "water", transcription: "/ˈwɔːtər/", translation: "вода", frequency: 147, example: "Can I have some water?" },
  { word: "never", transcription: "/ˈnevər/", translation: "никогда", frequency: 148, example: "I never eat meat." },
  { word: "three", transcription: "/θriː/", translation: "три", frequency: 149, example: "I have three brothers." },
  { word: "little", transcription: "/ˈlɪtl/", translation: "маленький, немного", frequency: 150, example: "I have a little dog." },
  { word: "help", transcription: "/help/", translation: "помогать, помощь", frequency: 151, example: "Can you help me, please?" },
  { word: "put", transcription: "/pʊt/", translation: "класть, ставить", frequency: 152, example: "Put the book on the table." },
  { word: "start", transcription: "/stɑːrt/", translation: "начинать, старт", frequency: 153, example: "Let's start the game now." },
  { word: "try", transcription: "/traɪ/", translation: "пытаться, пробовать", frequency: 154, example: "I will try my best." },
  { word: "end", transcription: "/end/", translation: "конец, заканчивать", frequency: 155, example: "The movie ends at nine." },
  { word: "become", transcription: "/bɪˈkʌm/", translation: "становиться", frequency: 156, example: "She wants to become a doctor." },
  { word: "begin", transcription: "/bɪˈɡɪn/", translation: "начинать", frequency: 157, example: "The class begins at eight." },
  { word: "those", transcription: "/ðoʊz/", translation: "те", frequency: 158, example: "Those shoes are very nice." },
  { word: "country", transcription: "/ˈkʌntri/", translation: "страна, деревня", frequency: 159, example: "France is a beautiful country." },
  { word: "always", transcription: "/ˈɔːlweɪz/", translation: "всегда", frequency: 160, example: "I always drink coffee." },
  { word: "name", transcription: "/neɪm/", translation: "имя, название", frequency: 161, example: "What is your name?" },
  { word: "away", transcription: "/əˈweɪ/", translation: "прочь, далеко", frequency: 162, example: "The store is far away." },
  { word: "leave", transcription: "/liːv/", translation: "уходить, оставлять", frequency: 163, example: "We leave home at seven." },
  { word: "run", transcription: "/rʌn/", translation: "бежать, бегать", frequency: 164, example: "I run every morning." },
  { word: "let", transcription: "/let/", translation: "позволять, пусть", frequency: 165, example: "Let me see your photo." },
  { word: "part", transcription: "/pɑːrt/", translation: "часть, роль", frequency: 166, example: "This is my favorite part." },
  { word: "school", transcription: "/skuːl/", translation: "школа", frequency: 167, example: "My kids go to school." },
  { word: "point", transcription: "/pɔɪnt/", translation: "точка, суть, указывать", frequency: 168, example: "What is your main point?" },
  { word: "read", transcription: "/riːd/", translation: "читать", frequency: 169, example: "I read a book at night." },
  { word: "change", transcription: "/tʃeɪndʒ/", translation: "менять, изменение", frequency: 170, example: "We need to change the plan." },
  { word: "close", transcription: "/kloʊz/", translation: "закрывать, близкий", frequency: 171, example: "Please close the door." },
  { word: "play", transcription: "/pleɪ/", translation: "играть, игра", frequency: 172, example: "The children play outside." },
  { word: "learn", transcription: "/lɜːrn/", translation: "учить, узнавать", frequency: 173, example: "I want to learn English." },
  { word: "add", transcription: "/æd/", translation: "добавлять", frequency: 174, example: "Add some sugar to the tea." },
  { word: "follow", transcription: "/ˈfɒloʊ/", translation: "следовать, следить", frequency: 175, example: "Follow me, please." },
  { word: "ask", transcription: "/æsk/", translation: "спрашивать, просить", frequency: 176, example: "Can I ask a question?" },
  { word: "city", transcription: "/ˈsɪti/", translation: "город", frequency: 177, example: "I live in a big city." },
  { word: "open", transcription: "/ˈoʊpən/", translation: "открывать, открытый", frequency: 178, example: "Please open the window." },
  { word: "live", transcription: "/lɪv/", translation: "жить", frequency: 179, example: "They live near the park." },
  { word: "seem", transcription: "/siːm/", translation: "казаться", frequency: 180, example: "You seem very tired today." },
  { word: "side", transcription: "/saɪd/", translation: "сторона, бок", frequency: 181, example: "Sit on this side." },
  { word: "set", transcription: "/set/", translation: "устанавливать, набор", frequency: 182, example: "Set the cup on the shelf." },
  { word: "few", transcription: "/fjuː/", translation: "немногие, мало", frequency: 183, example: "I have a few friends." },
  { word: "both", transcription: "/boʊθ/", translation: "оба", frequency: 184, example: "Both books are good." },
  { word: "write", transcription: "/raɪt/", translation: "писать", frequency: 185, example: "I write a letter every week." },
  { word: "important", transcription: "/ɪmˈpɔːrtənt/", translation: "важный", frequency: 186, example: "This is a very important day." },
  { word: "enough", transcription: "/ɪˈnʌf/", translation: "достаточно", frequency: 187, example: "We have enough food." },
  { word: "far", transcription: "/fɑːr/", translation: "далёкий, далеко", frequency: 188, example: "The school is not far." },
  { word: "young", transcription: "/jʌŋ/", translation: "молодой", frequency: 189, example: "She is still very young." },
  { word: "early", transcription: "/ˈɜːrli/", translation: "ранний, рано", frequency: 190, example: "I wake up early." },
  { word: "family", transcription: "/ˈfæməli/", translation: "семья", frequency: 191, example: "I love my family." },
  { word: "stand", transcription: "/stænd/", translation: "стоять", frequency: 192, example: "Please stand near the wall." },
  { word: "light", transcription: "/laɪt/", translation: "свет, лёгкий", frequency: 193, example: "Turn on the light." },
  { word: "later", transcription: "/ˈleɪtər/", translation: "позже, позднее", frequency: 194, example: "I will call you later." },
  { word: "country", transcription: "/ˈkʌntri/", translation: "страна", frequency: 195, example: "France is a beautiful country." },
  { word: "story", transcription: "/ˈstɔːri/", translation: "история, рассказ", frequency: 196, example: "Tell me a story." },
  { word: "fact", transcription: "/fækt/", translation: "факт", frequency: 197, example: "That is an interesting fact." },
  { word: "money", transcription: "/ˈmʌni/", translation: "деньги", frequency: 198, example: "I have no money today." },
  { word: "problem", transcription: "/ˈprɒbləm/", translation: "проблема", frequency: 199, example: "We have a small problem." },
  { word: "idea", transcription: "/aɪˈdɪə/", translation: "идея, мысль", frequency: 200, example: "I have a good idea." },
  // 201-350 - more useful vocabulary
  { word: "believe", transcription: "/bɪˈliːv/", translation: "верить, полагать", frequency: 201, example: "I believe you can do it." },
  { word: "power", transcription: "/ˈpaʊər/", translation: "сила, власть", frequency: 202, example: "The storm cut off the power." },
  { word: "watch", transcription: "/wɒtʃ/", translation: "смотреть, часы", frequency: 203, example: "Let's watch a movie tonight." },
  { word: "remember", transcription: "/rɪˈmembər/", translation: "помнить, вспоминать", frequency: 204, example: "I remember her birthday." },
  { word: "often", transcription: "/ˈɒfən/", translation: "часто", frequency: 205, example: "We often eat together." },
  { word: "stop", transcription: "/stɒp/", translation: "останавливать", frequency: 206, example: "Please stop the car here." },
  { word: "talk", transcription: "/tɔːk/", translation: "разговаривать, беседа", frequency: 207, example: "Let's talk after lunch." },
  { word: "experience", transcription: "/ɪkˈspɪəriəns/", translation: "опыт, переживание", frequency: 208, example: "It was a great experience." },
  { word: "body", transcription: "/ˈbɒdi/", translation: "тело", frequency: 209, example: "Exercise keeps your body strong." },
  { word: "question", transcription: "/ˈkwestʃən/", translation: "вопрос", frequency: 210, example: "May I ask a question?" },
  { word: "morning", transcription: "/ˈmɔːrnɪŋ/", translation: "утро", frequency: 211, example: "I drink coffee every morning." },
  { word: "reach", transcription: "/riːtʃ/", translation: "достигать, добираться", frequency: 212, example: "I can't reach the top shelf." },
  { word: "stay", transcription: "/steɪ/", translation: "оставаться", frequency: 213, example: "Please stay here with me." },
  { word: "understand", transcription: "/ˌʌndərˈstænd/", translation: "понимать", frequency: 214, example: "I understand the problem now." },
  { word: "door", transcription: "/dɔːr/", translation: "дверь", frequency: 215, example: "Please close the door." },
  { word: "bring", transcription: "/brɪŋ/", translation: "приносить", frequency: 216, example: "Bring your book to class." },
  { word: "happen", transcription: "/ˈhæpən/", translation: "случаться, происходить", frequency: 217, example: "What will happen next?" },
  { word: "hold", transcription: "/hoʊld/", translation: "держать, удерживать", frequency: 218, example: "Hold my hand, please." },
  { word: "speak", transcription: "/spiːk/", translation: "говорить, разговаривать", frequency: 219, example: "Do you speak English?" },
  { word: "real", transcription: "/rɪəl/", translation: "настоящий, реальный", frequency: 220, example: "Is this gold real?" },
  { word: "mean", transcription: "/miːn/", translation: "означать, иметь в виду", frequency: 221, example: "What does this word mean?" },
  { word: "grow", transcription: "/ɡroʊ/", translation: "расти, выращивать", frequency: 222, example: "Plants grow in the sun." },
  { word: "build", transcription: "/bɪld/", translation: "строить, создавать", frequency: 223, example: "They build new houses here." },
  { word: "earth", transcription: "/ɜːrθ/", translation: "земля, планета", frequency: 224, example: "The earth is very old." },
  { word: "possible", transcription: "/ˈpɒsəbl/", translation: "возможный", frequency: 225, example: "Is it possible to fix this?" },
  { word: "answer", transcription: "/ˈænsər/", translation: "ответ, отвечать", frequency: 226, example: "I know the right answer." },
  { word: "receive", transcription: "/rɪˈsiːv/", translation: "получать, принимать", frequency: 227, example: "Did you receive my letter?" },
  { word: "study", transcription: "/ˈstʌdi/", translation: "изучать, учёба", frequency: 228, example: "I study English every day." },
  { word: "develop", transcription: "/dɪˈveləp/", translation: "развивать, разрабатывать", frequency: 229, example: "They develop new apps." },
  { word: "human", transcription: "/ˈhjuːmən/", translation: "человеческий, человек", frequency: 230, example: "Every human needs water." },
  { word: "food", transcription: "/fuːd/", translation: "еда, пища", frequency: 231, example: "The food smells delicious." },
  { word: "spend", transcription: "/spend/", translation: "тратить, проводить", frequency: 232, example: "I spend too much money." },
  { word: "language", transcription: "/ˈlæŋɡwɪdʒ/", translation: "язык (речь)", frequency: 233, example: "English is a useful language." },
  { word: "mother", transcription: "/ˈmʌðər/", translation: "мать", frequency: 234, example: "My mother cooks dinner." },
  { word: "father", transcription: "/ˈfɑːðər/", translation: "отец", frequency: 235, example: "My father drives to work." },
  { word: "friend", transcription: "/frend/", translation: "друг", frequency: 236, example: "She is my best friend." },
  { word: "woman", transcription: "/ˈwʊmən/", translation: "женщина", frequency: 237, example: "That woman is a doctor." },
  { word: "child", transcription: "/tʃaɪld/", translation: "ребёнок", frequency: 238, example: "The child is sleeping." },
  { word: "table", transcription: "/ˈteɪbl/", translation: "стол, таблица", frequency: 239, example: "Put the plates on the table." },
  { word: "walk", transcription: "/wɔːk/", translation: "ходить, гулять", frequency: 240, example: "Let's walk to the park." },
  { word: "white", transcription: "/waɪt/", translation: "белый", frequency: 241, example: "She wore a white dress." },
  { word: "black", transcription: "/blæk/", translation: "чёрный", frequency: 242, example: "He has a black cat." },
  { word: "strong", transcription: "/strɒŋ/", translation: "сильный, крепкий", frequency: 243, example: "He is very strong." },
  { word: "true", transcription: "/truː/", translation: "правдивый, верный", frequency: 244, example: "Is the story true?" },
  { word: "sure", transcription: "/ʃʊər/", translation: "уверенный, конечно", frequency: 245, example: "Are you sure about this?" },
  { word: "clear", transcription: "/klɪər/", translation: "ясный, чистый", frequency: 246, example: "The sky is clear today." },
  { word: "happy", transcription: "/ˈhæpi/", translation: "счастливый", frequency: 247, example: "I am very happy today." },
  { word: "beautiful", transcription: "/ˈbjuːtɪfl/", translation: "красивый", frequency: 248, example: "What a beautiful sunset!" },
  { word: "simple", transcription: "/ˈsɪmpl/", translation: "простой", frequency: 249, example: "This recipe is very simple." },
  { word: "free", transcription: "/friː/", translation: "свободный, бесплатный", frequency: 250, example: "The tickets are free today." },
  { word: "hard", transcription: "/hɑːrd/", translation: "трудный, твёрдый", frequency: 251, example: "This test is very hard." },
  { word: "behind", transcription: "/bɪˈhaɪnd/", translation: "позади, за", frequency: 252, example: "The cat hid behind the door." },
  { word: "listen", transcription: "/ˈlɪsn/", translation: "слушать", frequency: 253, example: "I listen to music every day." },
  { word: "create", transcription: "/kriˈeɪt/", translation: "создавать, творить", frequency: 254, example: "Let's create a new plan." },
  { word: "decide", transcription: "/dɪˈsaɪd/", translation: "решать", frequency: 255, example: "You must decide today." },
  { word: "explain", transcription: "/ɪkˈspleɪn/", translation: "объяснять", frequency: 256, example: "Can you explain this to me?" },
  { word: "wonder", transcription: "/ˈwʌndər/", translation: "удивляться, чудо", frequency: 257, example: "I wonder where she is." },
  { word: "consider", transcription: "/kənˈsɪdər/", translation: "рассматривать, считать", frequency: 258, example: "Please consider my idea." },
  { word: "suggest", transcription: "/səˈdʒest/", translation: "предлагать", frequency: 259, example: "I suggest we leave now." },
  { word: "continue", transcription: "/kənˈtɪnjuː/", translation: "продолжать", frequency: 260, example: "Let's continue the lesson." },
  { word: "expect", transcription: "/ɪkˈspekt/", translation: "ожидать", frequency: 261, example: "We expect good news soon." },
  { word: "produce", transcription: "/prəˈdjuːs/", translation: "производить", frequency: 262, example: "This farm produces fresh milk." },
  { word: "provide", transcription: "/prəˈvaɪd/", translation: "предоставлять", frequency: 263, example: "They provide free water here." },
  { word: "include", transcription: "/ɪnˈkluːd/", translation: "включать, содержать", frequency: 264, example: "The price includes breakfast." },
  { word: "require", transcription: "/rɪˈkwaɪər/", translation: "требовать", frequency: 265, example: "This job requires hard work." },
  { word: "agree", transcription: "/əˈɡriː/", translation: "соглашаться", frequency: 266, example: "I agree with you." },
  { word: "offer", transcription: "/ˈɒfər/", translation: "предлагать, предложение", frequency: 267, example: "They offer a good price." },
  { word: "prepare", transcription: "/prɪˈpeər/", translation: "готовить, подготавливать", frequency: 268, example: "I prepare dinner at six." },
  { word: "suppose", transcription: "/səˈpoʊz/", translation: "предполагать, полагать", frequency: 269, example: "I suppose you are right." },
  { word: "enjoy", transcription: "/ɪnˈdʒɔɪ/", translation: "наслаждаться", frequency: 270, example: "I enjoy reading books." },
  { word: "imagine", transcription: "/ɪˈmædʒɪn/", translation: "воображать, представлять", frequency: 271, example: "Imagine a quiet beach." },
  { word: "accept", transcription: "/əkˈsept/", translation: "принимать, соглашаться", frequency: 272, example: "Please accept my gift." },
  { word: "allow", transcription: "/əˈlaʊ/", translation: "позволять, разрешать", frequency: 273, example: "They allow dogs in the park." },
  { word: "compare", transcription: "/kəmˈpeər/", translation: "сравнивать", frequency: 274, example: "Let's compare these two cars." },
  { word: "contain", transcription: "/kənˈteɪn/", translation: "содержать, вмещать", frequency: 275, example: "This box contains old photos." },
  { word: "choose", transcription: "/tʃuːz/", translation: "выбирать", frequency: 276, example: "You can choose any color." },
  { word: "surprise", transcription: "/sərˈpraɪz/", translation: "удивлять, сюрприз", frequency: 277, example: "The party was a big surprise." },
  { word: "protect", transcription: "/prəˈtekt/", translation: "защищать", frequency: 278, example: "We must protect the forest." },
  { word: "improve", transcription: "/ɪmˈpruːv/", translation: "улучшать", frequency: 279, example: "I want to improve my English." },
  { word: "destroy", transcription: "/dɪˈstrɔɪ/", translation: "разрушать, уничтожать", frequency: 280, example: "The storm destroyed the house." },
  { word: "describe", transcription: "/dɪˈskraɪb/", translation: "описывать", frequency: 281, example: "Can you describe the man?" },
  { word: "discover", transcription: "/dɪˈskʌvər/", translation: "обнаруживать, открывать", frequency: 282, example: "They discovered a new path." },
  { word: "involve", transcription: "/ɪnˈvɒlv/", translation: "вовлекать, включать", frequency: 283, example: "The plan involves everyone." },
  { word: "result", transcription: "/rɪˈzʌlt/", translation: "результат", frequency: 284, example: "I am happy with the result." },
  { word: "appear", transcription: "/əˈpɪər/", translation: "появляться, казаться", frequency: 285, example: "A star appeared in the sky." },
  { word: "achieve", transcription: "/əˈtʃiːv/", translation: "достигать, добиваться", frequency: 286, example: "You can achieve your goals." },
  { word: "knowledge", transcription: "/ˈnɒlɪdʒ/", translation: "знание", frequency: 287, example: "She has deep knowledge of art." },
  { word: "situation", transcription: "/ˌsɪtʃuˈeɪʃən/", translation: "ситуация, положение", frequency: 288, example: "This is a hard situation." },
  { word: "society", transcription: "/səˈsaɪəti/", translation: "общество", frequency: 289, example: "We live in a free society." },
  { word: "perhaps", transcription: "/pərˈhæps/", translation: "возможно, может быть", frequency: 290, example: "Perhaps it will rain today." },
  { word: "position", transcription: "/pəˈzɪʃən/", translation: "положение, позиция", frequency: 291, example: "He has a good position now." },
  { word: "history", transcription: "/ˈhɪstəri/", translation: "история", frequency: 292, example: "I love studying history." },
  { word: "attention", transcription: "/əˈtenʃən/", translation: "внимание", frequency: 293, example: "Please pay attention now." },
  { word: "common", transcription: "/ˈkɒmən/", translation: "общий, обычный", frequency: 294, example: "This is a common mistake." },
  { word: "various", transcription: "/ˈveəriəs/", translation: "различный, разнообразный", frequency: 295, example: "We sell various kinds of tea." },
  { word: "natural", transcription: "/ˈnætʃərəl/", translation: "природный, естественный", frequency: 296, example: "This juice is natural." },
  { word: "international", transcription: "/ˌɪntərˈnæʃənəl/", translation: "международный", frequency: 297, example: "It is an international school." },
  { word: "political", transcription: "/pəˈlɪtɪkəl/", translation: "политический", frequency: 298, example: "They watched a political show." },
  { word: "economic", transcription: "/ˌiːkəˈnɒmɪk/", translation: "экономический", frequency: 299, example: "The country has economic problems." },
  { word: "social", transcription: "/ˈsoʊʃəl/", translation: "социальный, общественный", frequency: 300, example: "She has many social events." },
  { word: "special", transcription: "/ˈspeʃəl/", translation: "особый, специальный", frequency: 301, example: "Today is a special day." },
  { word: "possible", transcription: "/ˈpɒsəbl/", translation: "возможный", frequency: 302, example: "Is it possible to fix this?" },
  { word: "available", transcription: "/əˈveɪləbl/", translation: "доступный, имеющийся", frequency: 303, example: "The room is available now." },
  { word: "necessary", transcription: "/ˈnesəsəri/", translation: "необходимый", frequency: 304, example: "Sleep is necessary for health." },
  { word: "difficult", transcription: "/ˈdɪfɪkəlt/", translation: "трудный, сложный", frequency: 305, example: "This test is very difficult." },
  { word: "significant", transcription: "/sɪɡˈnɪfɪkənt/", translation: "значительный, важный", frequency: 306, example: "We saw a significant change." },
  { word: "similar", transcription: "/ˈsɪmɪlər/", translation: "похожий, подобный", frequency: 307, example: "Our ideas are quite similar." },
  { word: "popular", transcription: "/ˈpɒpjʊlər/", translation: "популярный, народный", frequency: 308, example: "This song is very popular." },
  { word: "traditional", transcription: "/trəˈdɪʃənəl/", translation: "традиционный", frequency: 309, example: "We ate traditional food today." },
  { word: "environment", transcription: "/ɪnˈvaɪrənmənt/", translation: "окружающая среда", frequency: 310, example: "We must protect the environment." },
  { word: "technology", transcription: "/tekˈnɒlədʒi/", translation: "технология", frequency: 311, example: "New technology helps us work." },
  { word: "education", transcription: "/ˌedjʊˈkeɪʃən/", translation: "образование", frequency: 312, example: "Education is very important." },
  { word: "community", transcription: "/kəˈmjuːnəti/", translation: "сообщество", frequency: 313, example: "Our community is very friendly." },
  { word: "relationship", transcription: "/rɪˈleɪʃənʃɪp/", translation: "отношения, связь", frequency: 314, example: "They have a good relationship." },
  { word: "opportunity", transcription: "/ˌɒpərˈtjuːnəti/", translation: "возможность, шанс", frequency: 315, example: "This is a great opportunity." },
  { word: "responsibility", transcription: "/rɪˌspɒnsəˈbɪləti/", translation: "ответственность", frequency: 316, example: "Safety is your responsibility." },
  { word: "information", transcription: "/ˌɪnfərˈmeɪʃən/", translation: "информация", frequency: 317, example: "I need more information, please." },
  { word: "government", transcription: "/ˈɡʌvərnmənt/", translation: "правительство", frequency: 318, example: "The government built new roads." },
  { word: "development", transcription: "/dɪˈveləpmənt/", translation: "развитие", frequency: 319, example: "The city's development is fast." },
  { word: "management", transcription: "/ˈmænɪdʒmənt/", translation: "управление, менеджмент", frequency: 320, example: "Time management is a skill." },
  { word: "difference", transcription: "/ˈdɪfrəns/", translation: "разница, отличие", frequency: 321, example: "What is the difference here?" },
  { word: "performance", transcription: "/pərˈfɔːrməns/", translation: "выступление, производительность", frequency: 322, example: "Her performance was amazing." },
  { word: "conversation", transcription: "/ˌkɒnvərˈseɪʃən/", translation: "разговор, беседа", frequency: 323, example: "We had a long conversation." },
  { word: "temperature", transcription: "/ˈtemprətʃər/", translation: "температура", frequency: 324, example: "The temperature is rising fast." },
  { word: "comfortable", transcription: "/ˈkʌmftəbl/", translation: "удобный, комфортный", frequency: 325, example: "This chair is very comfortable." },
  { word: "dangerous", transcription: "/ˈdeɪndʒərəs/", translation: "опасный", frequency: 326, example: "That road is very dangerous." },
  { word: "independent", transcription: "/ˌɪndɪˈpendənt/", translation: "независимый", frequency: 327, example: "She is an independent woman." },
  { word: "unfortunately", transcription: "/ʌnˈfɔːrtʃənətli/", translation: "к сожалению", frequency: 328, example: "Unfortunately, the shop is closed." },
  { word: "immediately", transcription: "/ɪˈmiːdiətli/", translation: "немедленно, сразу", frequency: 329, example: "Please call me immediately." },
  { word: "especially", transcription: "/ɪˈspeʃəli/", translation: "особенно", frequency: 330, example: "I love fruit, especially apples." },
  { word: "absolutely", transcription: "/ˈæbsəluːtli/", translation: "абсолютно, совершенно", frequency: 331, example: "You are absolutely right." },
  { word: "actually", transcription: "/ˈæktʃuəli/", translation: "на самом деле, фактически", frequency: 332, example: "I actually like this idea." },
  { word: "certainly", transcription: "/ˈsɜːrtnli/", translation: "конечно, безусловно", frequency: 333, example: "I will certainly help you." },
  { word: "obviously", transcription: "/ˈɒbviəsli/", translation: "очевидно", frequency: 334, example: "He is obviously very tired." },
  { word: "probably", transcription: "/ˈprɒbəbli/", translation: "вероятно, наверное", frequency: 335, example: "It will probably rain today." },
  { word: "generally", transcription: "/ˈdʒenərəli/", translation: "обычно, в целом", frequency: 336, example: "I generally wake up early." },
  { word: "recently", transcription: "/ˈriːsntli/", translation: "недавно", frequency: 337, example: "I recently moved to London." },
  { word: "suddenly", transcription: "/ˈsʌdənli/", translation: "вдруг, внезапно", frequency: 338, example: "Suddenly, the lights went out." },
  { word: "completely", transcription: "/kəmˈpliːtli/", translation: "полностью, совершенно", frequency: 339, example: "I completely forgot the time." },
  { word: "eventually", transcription: "/ɪˈventʃuəli/", translation: "в конце концов", frequency: 340, example: "We eventually found the house." },
  { word: "apparently", transcription: "/əˈpærəntli/", translation: "по-видимому, очевидно", frequency: 341, example: "Apparently, she is leaving soon." },
  { word: "approximately", transcription: "/əˈprɒksɪmətli/", translation: "приблизительно", frequency: 342, example: "It costs approximately ten dollars." },
  { word: "meanwhile", transcription: "/ˈmiːnwaɪl/", translation: "тем временем", frequency: 343, example: "Meanwhile, I made some coffee." },
  { word: "therefore", transcription: "/ˈðeərfɔːr/", translation: "поэтому, следовательно", frequency: 344, example: "It rained; therefore we stayed home." },
  { word: "although", transcription: "/ɔːlˈðoʊ/", translation: "хотя, несмотря на", frequency: 345, example: "Although tired, she kept working." },
  { word: "however", transcription: "/haʊˈevər/", translation: "однако, тем не менее", frequency: 346, example: "I tried; however, I failed." },
  { word: "whether", transcription: "/ˈweðər/", translation: "ли, будь то", frequency: 347, example: "I don't know whether to go." },
  { word: "neither", transcription: "/ˈniːðər/", translation: "ни тот ни другой", frequency: 348, example: "Neither answer is correct." },
  { word: "nevertheless", transcription: "/ˌnevərðəˈles/", translation: "тем не менее, всё же", frequency: 349, example: "It was hard; nevertheless, we won." },
  { word: "extraordinary", transcription: "/ɪkˈstrɔːrdəneri/", translation: "необычайный, выдающийся", frequency: 350, example: "She has an extraordinary memory." },
]);

db.words.createIndex({ frequency: 1 });

print("Inserted " + db.words.countDocuments() + " words");
